### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [shibe97/react-awesome-modal#1]
Please guide me to scroll and view the overflowed content in the modal...

I am able add scroll bar by adding overlay:'scroll' in panel css which is in "fadeInUp.js"

Is there any other way to add scroll bar, because I don't want to change files in node modules.

**Comment by shibe97** [comment]
@HarshaVardhanPVK 
You can add scroll bar without changing files in node modules by writing your own css style.
I will give you an example.

React
```
<Modal visible={this.state.visible} width="300" height="400" effect="fadeInUp" >
    <div className="Modal">
         // something
    </div>
</Modal>
```

CSS
```
.Modal {
    height: 400px;
    overflow: auto;
}
```

**Comment by waliddamou** [comment]
shib97 you solution doesn't work bro
