### ISSUE TITLE
IE10 issue

### ISSUE THREAD

**Issue by steveodom** [shibe97/react-awesome-modal#2]
I'm getting an error in IE10. Here's is a link to an unadulterated build of the example.
https://s3.amazonaws.com/steveodom/modal-test/index.html

It dies on this.props. in setSize.

**Comment by shibe97** [comment]
@steveodom 
Thanks for reporting.
I confirmed and fixed this bug. https://github.com/shibe97/react-awesome-modal/commit/53dfa8fce491503ae178f8ba8feb604b72945b0e

Please update this package to new version 0.3.3.
