### ISSUE TITLE
In React 16.9 Getting Deprecation warning on componentWillReceiveProps

### ISSUE THREAD

**Issue by pkellner** [shibe97/react-awesome-modal#25]
Will this be updated to not use componentWillReceiveProps and then hopefully work when React 17 comes out?

**Comment by shibe97** [comment]
I created a new modal package which uses react hooks. It's easier and more intuitive.
Prease look at the new repository.

https://github.com/shibe97/react-hooks-use-modal

**Comment by irfancnk** [comment]
Instead of using 
`const [Modal, open, close] = useModal();`
To control the modal behaviour, isn't that more suitable using something similar to 
`visible`
for systems that is using its own state storage like Redux

**Comment by shibe97** [comment]
I think `visible` state should be controlled in component.
We only need `open` and `close` functions.
