### ISSUE TITLE
onClickAway() function

### ISSUE THREAD

**Issue by manalj** [shibe97/react-awesome-modal#6]
Is there anyway you can add a listener on the overlay, to close the modal when I click away?

**Comment by shibe97** [comment]
you can add an event listener in the modal like this.
```
closeModal() {
    this.setState({
        visible : false
    });
}

render() {
    return (
        <Modal visible={this.state.visible} width="400" height="300" effect="fadeInUp">
            <a href="javascript:void(0);" onClick={this.closeModal.bind(this)}>Close</a>
        </Modal>
    );
}
```

Does it make sense?

**Comment by manalj** [comment]
I'm talking about closing the modal when clicking outside the modal

<img width="1234" alt="screen shot 2016-07-11 at 3 08 07 pm" src="https://cloud.githubusercontent.com/assets/9582819/16733488/b13040a8-4779-11e6-9329-33c5550a85c8.png">

How can I do that?

**Comment by shibe97** [comment]
I understood your question.
Now, there is no way to close the modal when clicking outside the modal.

I'll add an option which can set an event listener to the background mask.
Or, welcome pull requests.
